initialize-release
haloStyles

	(self for: #haloButton)
		color: #fff;
		borderRadius: 999;
		padding: 10;
		borderWidth: 0.
		
	(self for: #(haloButton haloGrowHandle))
		backgroundColor: '#FDD835';
		color: #'000'.
		
	(self for: #(haloButton haloDismissHandle))
		backgroundColor: '#F4511E'.
	
	(self for: #(haloButton haloDuplicateHandle))
		backgroundColor: #'7CB342'.
	
	(self for: #(haloButton haloDebugHandle))
		backgroundColor: #'757575'.
	
	(self for: #(haloButton haloGrabHandle))
		backgroundColor: #'546E7A'.
	
	(self for: #(haloButton haloLayoutHandle))
		backgroundColor: #'1E88E5'.
	
	(self for: #(haloButton haloFontHandle))
		backgroundColor: #'8E24AA'